### ISSUE TITLE
stl files

### ISSUE THREAD

**Issue by Nightshadow1258** [jakkra/RoverController#1]
not really an issue, but I would really like to  rebuild the controller. Since I don't have Fusion 360 could you maybe provide the .stl files for all the parts? 
That would be awesome!

Thanks in advance.

**Comment by jakkra** [comment]
Fusion 360 is free for personal use so you could download it for free. But sure, I can export the STL files tomorrow, no problem.

**Comment by Nightshadow1258** [comment]
Oh I did not know that. I will donwload and export it myself than, no worries!
Thanks

**Comment by jakkra** [comment]
Ok nice, come back if you can't get it to work

**Comment by felixsteghofer** [comment]
@jakkra Would be very nice to also supply the stl files (on linux here and fusion in a vm is hardly usable)

**Comment by jakkra** [comment]
@felixsteghofer OK, I will export the controller STL files, however I can't do it until the weekend.
